const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const PACKS={mini:{title:"MINI 3",price:299000,image:"assets/pack-mini.webp",text:"Muro de escalada bajo y zona amortiguante. Una entrada simple para activar una pared y mantener el resto del espacio libre."},active:{title:"ACTIVO 6",price:549000,image:"assets/pack-active.webp",text:"Muro de travesía, espaldera, red y superficie amortiguante. Diseñado para concentrar la actividad en el perímetro y dejar el centro libre."},adventure:{title:"AVENTURA 10",price:899000,image:"assets/pack-adventure.webp",text:"Un circuito más completo con escalada, barras, red, anillas y guardado. Pensado para ofrecer más rutas y crecer por módulos."}};
let selectedPack="active";
const clp=v=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(v);
function updateEstimate(){let total=PACKS[selectedPack].price;$$("[data-addon]:checked").forEach(i=>total+=Number(i.dataset.addon));$("#estimatePrice").textContent=clp(total)}
function selectPack(key){selectedPack=key;$$(".config-option").forEach(b=>b.classList.toggle("active",b.dataset.pack===key));$("#previewPackLabel").textContent=PACKS[key].title;updateEstimate()}
$$(".config-option").forEach(b=>b.addEventListener("click",()=>selectPack(b.dataset.pack)));$$("[data-addon]").forEach(i=>i.addEventListener("change",updateEstimate));
const input=$("#photoInput"),dropzone=$("#dropzone"),preview=$("#photoPreview"),previewImage=$("#previewImage");
function loadPhoto(file){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){alert("Usa una imagen JPG, PNG o WEBP.");return}if(file.size>10*1024*1024){alert("La imagen supera 10 MB.");return}const reader=new FileReader();reader.onload=e=>{previewImage.src=e.target.result;dropzone.hidden=true;preview.hidden=false};reader.readAsDataURL(file)}
dropzone.addEventListener("click",()=>input.click());dropzone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();input.click()}});input.addEventListener("change",e=>loadPhoto(e.target.files[0]));["dragenter","dragover"].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.add("dragover")}));["dragleave","drop"].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.remove("dragover")}));dropzone.addEventListener("drop",e=>loadPhoto(e.dataTransfer.files[0]));$("#changePhoto").addEventListener("click",()=>input.click());
$("#renderButton").addEventListener("click",()=>{const p=PACKS[selectedPack];$("#renderImage").src=p.image;$("#renderImage").alt="Referencia visual del pack "+p.title;$("#renderBadge").textContent=p.title;$("#renderTitle").textContent=p.title;$("#renderText").textContent=p.text;$("#renderResult").scrollIntoView({behavior:"smooth",block:"center"})});
const menuButton=$(".menu-toggle"),nav=$("#main-nav");menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});$$('#main-nav a').forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});$$(".reveal").forEach(el=>observer.observe(el));$("#year").textContent=new Date().getFullYear();updateEstimate();