const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const PACKS={mini:{title:"MINI 3",price:549000,image:"assets/pack-mini.webp",text:"Una pared que empieza a jugar: muro compacto, presas, ruta inicial y una zona amortiguante acotada. Ideal para validar el concepto sin ocupar todo el patio."},active:{title:"ACTIVO 6",price:1190000,image:"assets/pack-active.webp",text:"Concentra escalada, trepa y suspensión en el perímetro para dejar el centro libre. Es la configuración que mejor equilibra impacto visual, juego y superficie ocupada."},adventure:{title:"AVENTURA 10",price:1990000,image:"assets/pack-adventure.webp",text:"Circuito ampliado con más recorrido, suspensión, red y posibilidad de guardado. Pensado para patios donde vale la pena construir una experiencia más completa."}};
let selectedPack="active";const clp=v=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(v);
function updateEstimate(){let total=PACKS[selectedPack].price;$$("[data-addon]:checked").forEach(i=>total+=Number(i.dataset.addon));$("#estimatePrice").textContent=clp(total)}
function selectPack(key){selectedPack=key;$$(".config-option").forEach(b=>b.classList.toggle("active",b.dataset.pack===key));const label=$("#previewPackLabel");if(label)label.textContent=PACKS[key].title;updateEstimate()}
$$(".config-option").forEach(b=>b.addEventListener("click",()=>selectPack(b.dataset.pack)));$$("[data-addon]").forEach(i=>i.addEventListener("change",updateEstimate));
const input=$("#photoInput"),dropzone=$("#dropzone"),preview=$("#photoPreview"),previewImage=$("#previewImage");
function loadPhoto(file){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){alert("Usa una imagen JPG, PNG o WEBP.");return}if(file.size>10*1024*1024){alert("La imagen supera 10 MB.");return}const reader=new FileReader();reader.onload=e=>{previewImage.src=e.target.result;dropzone.hidden=true;preview.hidden=false};reader.readAsDataURL(file)}
if(dropzone&&input){dropzone.addEventListener("click",()=>input.click());dropzone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();input.click()}});input.addEventListener("change",e=>loadPhoto(e.target.files[0]));["dragenter","dragover"].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.add("dragover")}));["dragleave","drop"].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.remove("dragover")}));dropzone.addEventListener("drop",e=>loadPhoto(e.dataTransfer.files[0]))}
const change=$("#changePhoto");if(change)change.addEventListener("click",()=>input.click());
const render=$("#renderButton");if(render)render.addEventListener("click",()=>{const p=PACKS[selectedPack];$("#renderImage").src=p.image;$("#renderImage").alt="Referencia visual de "+p.title;$("#renderBadge").textContent=p.title;$("#renderTitle").textContent=p.title;$("#renderText").textContent=p.text;$("#renderResult").scrollIntoView({behavior:"smooth",block:"center"})});
const menuButton=$(".menu-toggle"),nav=$("#main-nav");if(menuButton&&nav){menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});$$('#main-nav a').forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}))}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.1});$$(".reveal").forEach(el=>observer.observe(el));const year=$("#year");if(year)year.textContent=new Date().getFullYear();updateEstimate();